### ISSUE TITLE
the build doesnt generate the proper paths for styles.css and bundle.js

### ISSUE THREAD

**Issue by kevohagan** [hb-gatsby/gatsby-lumen-starter#1]
just tried on a fresh install. great starter though! :)

**Comment by wpioneer** [comment]
I think you have to rebuild the bundle.

In any case, I removed _Public_ dir from the repository. https://github.com/hb-gatsby/gatsby-lumen-starter/commit/a75d2862b96b8e665b362f610b4b3c870529258a
